### ISSUE TITLE
Dependencies breaking 

### ISSUE THREAD

**Issue by fergusleen** [foxhound87/mobx-react-form-demo#12]
Hi, I'm getting the following error on npm install.

npm WARN react-json-tree@0.10.9 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-json-tree@0.10.9 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-widgets@4.0.3 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-widgets@4.0.3 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by foxhound87** [comment]
Thank You for reporting this. 

I'm still unable to fix all warning related to React 16 right now, some deps need to be updated, but I will release more fix about React 16 in the future as the updates comes.
