### ISSUE TITLE
radio example

### ISSUE THREAD

**Issue by Gi972** [foxhound87/mobx-react-form-demo#14]
Hello @foxhound87 ,  

Can you make on codesanbox and on the doc , a example with radiobutton please?

Thank you

**Comment by Nodios** [comment]
You can find some examples here [here](https://github.com/foxhound87/mobx-react-form/issues/288). Also stated in the link: 

> The package doesn't provide a full support to Radio Buttons yet. I still don't know the right implementation, but I will find a way to properly support them. Thank you all for your use cases. PRs or other analysis are welcome!
