### ISSUE TITLE
Can not install app....

### ISSUE THREAD

**Issue by alenskupnjak** [foxhound87/mobx-react-form-demo#19]
Hello @foxhound87 ,

I got a message:

$ git submodule update
Cloning into 'C:/mobx-react-form-demo/modules/devtools'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:foxhound87/mobx-react-form-devtools.git' into submodule path 'C:/mobx-react-form-demo/modules/devtools' failed
Failed to clone 'modules/devtools'. Retry scheduled
Cloning into 'C:/mobx-react-form-demo/modules/form'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:foxhound87/mobx-react-form.git' into submodule path 'C:/mobx-react-form-demo/modules/form' failed
Failed to clone 'modules/form'. Retry scheduled
Cloning into 'C:/mobx-react-form-demo/modules/devtools'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:foxhound87/mobx-react-form-devtools.git' into submodule path 'C:/mobx-react-form-demo/modules/devtools' failed      
Failed to clone 'modules/devtools' a second time, aborting

**Comment by foxhound87** [comment]
you have to configure ssh keys in your system
