### ISSUE TITLE
resetValidation is not a function

### ISSUE THREAD

**Issue by benjamingeorge** [foxhound87/mobx-react-form-demo#5]
I found a bug.  It can be reproduced in your NestedFields demo online as well. 
In the Hobbies field, if a text field has focus (cursor in it), and you click the Delete button for that focused field, an error in the console will appear. ` g.resetValidation is not a function`.  In my own app, when doing the same thing, i get the same error `Validator.js Uncaught (in promise) TypeError: $field.resetValidation is not a function`

The same error occurs with a normal `<input type="text" {...field.bind()} />`

If you remove focus (blur) the textfield then click delete there is no error.

**Comment by foxhound87** [comment]
Thank you for reporting this. I will look into that
