### ISSUE TITLE
question: how to handle onChange events

### ISSUE THREAD

**Issue by jamhus** [foxhound87/mobx-react-form-demo#7]
hi
i am trying the mobx react form and i didn't find anything abouthandling the input onChange events

this is my code
`
import MobxReactForm from 'mobx-react-form';
import validatorjs from 'validatorjs';

const plugins = { dvr: validatorjs };

const fields = [{
    name: 'username',
    label: 'Username',
    placeholder: 'Insert Username',
    rules: 'required|email|string|between:5,25',
}, {
    name: 'password',
    label: 'Password',
    placeholder: 'Insert Password',
    rules: 'required|string|between:5,25',
}, {
    name: 'passwordConfirm',
    label: 'Password Confirmation',
    placeholder: 'Confirm Password',
    rules: 'same:password',
}];

class MyForm extends MobxReactForm {

    onSuccess(form) {
        alert('Form is valid! Send the request here.');
        // get field values
        console.log('Form Values!', form.values());
    }

    onError(form) {
        // get all form errors
        console.log('All form errors', form.errors());
        // invalidate the form with a custom error message
        form.invalidate('This is a generic error message!');
    }
}

const form = new MyForm({ fields }, { plugins });

export default form;
`import React from 'react';
import { observer } from 'mobx-react';

export default observer(({ field, type = 'text', placeholder = null }) => (
    <div className="measure">
        <label
            htmlFor={field.id}
            className="f7 db mb2 mt3 light-silver"
        >
            {field.label}
        </label>
        <input
            className="input-reset ba b--black-10 br1 pa2 mb2 db w-100 f6"
            aria-describedby="name-desc"
            {...field.bind({ type, placeholder }) }
        />
        <small className="f6 black-60 db red">
            {field.error}
        </small>
    </div>
));`
`import React from 'react';
import { observer } from 'mobx-react';
import MobxReactFormDevTools from 'mobx-react-form-devtools';
import Input from './SimpleInput';
import form from "./mobxReactForm";

MobxReactFormDevTools.register({
  form,
});

// select form to show into the devtools
MobxReactFormDevTools.select('form');

// open the devtools (closed by default)
MobxReactFormDevTools.open(true);

const App = observer(({Form}) => (
     <div>
      <form onSubmit={form.onSubmit}>
      <Input field={form.$('username')} />

        <p>{form.$('username').error}</p>

        ...

    <button type="submit" onClick={form.onSubmit}>Submit</button>
        <button type="button" onClick={form.onClear}>Clear</button>
        <button type="button" onClick={form.onReset}>Reset</button>

        <p>{form.error}</p>
      </form>
      <MobxReactFormDevTools.UI />
      </div>  
)
)

export default App;

`
any help would be appreciated !

**Comment by foxhound87** [comment]
When you use the `bind()` method on your input component, it will automatically use the default `onChange` Event Handler of the package. It works for most of the conventional inputs cases. If you want to override it, you can easily do it as explained here: https://foxhound87.github.io/mobx-react-form/docs/bindings/default.html#properties-overwrite

This is a simple example:

#### Define an Event Handler:
```javascript
const handleOnChange = field => (e) => {
  // very simplified, the package already do this automatically
  field.set(e.target.value); 
}
```

#### Use it the component:
```javascript
<input {...field.bind({ onChange: handleOnChange(field) })} />
```

**Comment by jamhus** [comment]
Hi 
i ran into another problem ,
i downloaded the demo and created my own forms in the same way that the other forms were created in , but the problem is that i can not switch between my own forms , i have to ope one of the forms created by you in order to switch to another form of mine!

**Comment by anusree-mmlab** [comment]
Is it possible to get a simple working code of this? The code in the documentation is not executable. Coz it needs the onSubmit and other required functions. Can anyone please help me?

**Comment by foxhound87** [comment]
Hi @anusree-mmlab, made it with custom `onChange`, you can also find the whole form structure:

[![Edit form-onChange](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/98r3x5vv4?module=%2Fcomponents%2Finputs%2FSimpleInput.js)
