### ISSUE TITLE
White space not trimmed in text fields

### ISSUE THREAD

**Issue by mdansei** [foxhound87/mobx-react-form-demo#9]
Hi @foxhound87, I've noticed there's no trimming for white space in the text fields :
![image](https://user-images.githubusercontent.com/16231649/27179500-94eaea1a-51d7-11e7-87ec-6d0355d890e2.png)

The reason being is a white space in the end. 

Is there a quick way to fix it, or I have to extend my own rule ?

**Comment by foxhound87** [comment]
The values are not trimmed automatically, so you are right, a custom rule is needed.

**Comment by foxhound87** [comment]
https://github.com/foxhound87/mobx-react-form/issues/283
